export interface CollectionItem {
  id: string;
  title: string;
  description: string;
  moodTag: string;
  icon: string;
  duration: string;
  imageUri?: string; // URL for mock image (uses picsum if not provided)
  audioPath?: string; // Path to audio file (you'll update this)
  category: string;
}

export interface CollectionCategory {
  id: string;
  title: string;
  description: string;
  moodTag: string;
  icon: string;
  itemCount: number;
  colors: [string, string];
}

// Collection categories
export const collectionCategories: CollectionCategory[] = [
  {
    id: "yoga-sutras",
    title: "Yoga Sutras",
    description:
      "Ancient wisdom for modern living, exploring Patanjali's timeless teachings.",
    moodTag: "Wisdom",
    icon: "🧘",
    itemCount: 7,
    colors: ["#4A3F55", "#2A2530"],
  },
  {
    id: "modern-gita",
    title: "Modern Gita",
    description:
      "The Bhagavad Gita reimagined for today's challenges and dilemmas.",
    moodTag: "Guidance",
    icon: "📿",
    itemCount: 18,
    colors: ["#5A4422", "#2B2010"],
  },
  {
    id: "modern-reset",
    title: "Modern Reset",
    description: "Quick practices to reset your mind in our always-on world.",
    moodTag: "Reset",
    icon: "🔄",
    itemCount: 5,
    colors: ["#273A57", "#151A2D"],
  },
  {
    id: "lifestyle-os",
    title: "Lifestyle OS",
    description: "Operating system for a balanced, intentional life.",
    moodTag: "Lifestyle",
    icon: "🌱",
    itemCount: 6,
    colors: ["#2D5A4C", "#172D27"],
  },
  {
    id: "9-problems-9-solutions",
    title: "9 Problems, 9 Solutions",
    description: "Practical wisdom for life's most common struggles.",
    moodTag: "Solutions",
    icon: "💡",
    itemCount: 10,
    colors: ["#684B25", "#2B1E0F"],
  },
];

// Collection items - PLACE YOUR VIDEOS IN: assets/videos/[category-id]/
// Then update the videoPath like: videoPath: require('../assets/videos/yoga-sutras/intro.mp4')

export const collectionItems: Record<string, CollectionItem[]> = {
  "yoga-sutras": [
    {
      id: "ys-1",
      title: "Introduction to Yoga Sutras",
      description: "Understanding the foundation of Patanjali's wisdom.",
      moodTag: "Foundation",
      icon: "🌟",
      duration: "12:30",
      category: "yoga-sutras",
      // videoPath: require('../assets/videos/yoga-sutras/01-intro.mp4'),
    },
    {
      id: "ys-2",
      title: "The Eight Limbs",
      description: "Exploring the eightfold path of yoga.",
      moodTag: "Path",
      icon: "🛤️",
      duration: "15:45",
      category: "yoga-sutras",
      // videoPath: require('../assets/videos/yoga-sutras/02-eight-limbs.mp4'),
    },
    {
      id: "ys-3",
      title: "Yamas - Universal Ethics",
      description: "The five moral restraints for harmonious living.",
      moodTag: "Ethics",
      icon: "🤝",
      duration: "18:20",
      category: "yoga-sutras",
      // videoPath: require('../assets/videos/yoga-sutras/03-yamas.mp4'),
    },
    {
      id: "ys-4",
      title: "Niyamas - Personal Observances",
      description: "Five practices for self-discipline and inner growth.",
      moodTag: "Discipline",
      icon: "🔥",
      duration: "16:15",
      category: "yoga-sutras",
      // videoPath: require('../assets/videos/yoga-sutras/04-niyamas.mp4'),
    },
    {
      id: "ys-5",
      title: "Asana and Pranayama",
      description: "Physical postures and breath control practices.",
      moodTag: "Practice",
      icon: "🧘‍♂️",
      duration: "20:00",
      category: "yoga-sutras",
      // videoPath: require('../assets/videos/yoga-sutras/05-asana-pranayama.mp4'),
    },
    {
      id: "ys-6",
      title: "Pratyahara and Dharana",
      description: "Withdrawal of senses and focused concentration.",
      moodTag: "Focus",
      icon: "🎯",
      duration: "14:30",
      category: "yoga-sutras",
      // videoPath: require('../assets/videos/yoga-sutras/06-pratyahara.mp4'),
    },
    {
      id: "ys-7",
      title: "Samadhi - Ultimate Absorption",
      description: "The state of complete meditation and unity.",
      moodTag: "Unity",
      icon: "☀️",
      duration: "22:10",
      category: "yoga-sutras",
      // videoPath: require('../assets/videos/yoga-sutras/07-samadhi.mp4'),
    },
  ],
  "modern-gita": [
    {
      id: "mg-1",
      title: "The Modern Arjuna",
      description: "Finding yourself in the battlefield of modern life.",
      moodTag: "Identity",
      icon: "⚔️",
      duration: "14:20",
      category: "modern-gita",
      // videoPath: require('../assets/videos/modern-gita/01-modern-arjuna.mp4'),
    },
    {
      id: "mg-2",
      title: "Karma Without Attachment",
      description: "Action without expectation of results.",
      moodTag: "Action",
      icon: "🎭",
      duration: "16:45",
      category: "modern-gita",
      // videoPath: require('../assets/videos/modern-gita/02-karma.mp4'),
    },
    {
      id: "mg-3",
      title: "The Art of Right Action",
      description: "Making decisions aligned with your dharma.",
      moodTag: "Dharma",
      icon: "🧭",
      duration: "18:30",
      category: "modern-gita",
      // videoPath: require('../assets/videos/modern-gita/03-right-action.mp4'),
    },
    {
      id: "mg-4",
      title: "Equanimity in Success and Failure",
      description: "Staying balanced through life's ups and downs.",
      moodTag: "Balance",
      icon: "⚖️",
      duration: "15:15",
      category: "modern-gita",
      // videoPath: require('../assets/videos/modern-gita/04-equanimity.mp4'),
    },
    {
      id: "mg-5",
      title: "The Three Gunas",
      description: "Understanding the qualities that shape our nature.",
      moodTag: "Nature",
      icon: "🌈",
      duration: "19:00",
      category: "modern-gita",
      // videoPath: require('../assets/videos/modern-gita/05-gunas.mp4'),
    },
    {
      id: "mg-6",
      title: "Devotion and Surrender",
      description: "The power of letting go and trusting the process.",
      moodTag: "Surrender",
      icon: "🙏",
      duration: "17:25",
      category: "modern-gita",
      // videoPath: require('../assets/videos/modern-gita/06-devotion.mp4'),
    },
    {
      id: "mg-7",
      title: "The Universal Form",
      description: "Seeing the divine in everything around you.",
      moodTag: "Vision",
      icon: "👁️",
      duration: "21:10",
      category: "modern-gita",
      // videoPath: require('../assets/videos/modern-gita/07-universal-form.mp4'),
    },
    {
      id: "mg-8",
      title: "Mastery Over the Mind",
      description: "Taming the restless mind through practice.",
      moodTag: "Mastery",
      icon: "🧠",
      duration: "16:40",
      category: "modern-gita",
      // videoPath: require('../assets/videos/modern-gita/08-mind-mastery.mp4'),
    },
    {
      id: "mg-9",
      title: "The Tree of Life",
      description: "Understanding the cycle of existence.",
      moodTag: "Existence",
      icon: "🌳",
      duration: "18:55",
      category: "modern-gita",
      // videoPath: require('../assets/videos/modern-gita/09-tree-of-life.mp4'),
    },
    {
      id: "mg-10",
      title: "Faith and Reason",
      description: "Balancing devotion with discernment.",
      moodTag: "Wisdom",
      icon: "💫",
      duration: "15:30",
      category: "modern-gita",
      // videoPath: require('../assets/videos/modern-gita/10-faith-reason.mp4'),
    },
    {
      id: "mg-11",
      title: "The Field and the Knower",
      description: "Distinguishing between matter and consciousness.",
      moodTag: "Consciousness",
      icon: "🌌",
      duration: "20:15",
      category: "modern-gita",
      // videoPath: require('../assets/videos/modern-gita/11-field-knower.mp4'),
    },
    {
      id: "mg-12",
      title: "The Three Yogas",
      description: "Karma, Jnana, and Bhakti paths to liberation.",
      moodTag: "Paths",
      icon: "🛤️",
      duration: "22:45",
      category: "modern-gita",
      // videoPath: require('../assets/videos/modern-gita/12-three-yogas.mp4'),
    },
    {
      id: "mg-13",
      title: "Divine and Demonic Natures",
      description: "Recognizing the qualities that elevate or degrade us.",
      moodTag: "Choice",
      icon: "😇",
      duration: "17:20",
      category: "modern-gita",
      // videoPath: require('../assets/videos/modern-gita/13-divine-demonic.mp4'),
    },
    {
      id: "mg-14",
      title: "Beyond the Gunas",
      description: "Transcending the three modes of nature.",
      moodTag: "Transcendence",
      icon: "🦅",
      duration: "19:35",
      category: "modern-gita",
      // videoPath: require('../assets/videos/modern-gita/14-beyond-gunas.mp4'),
    },
    {
      id: "mg-15",
      title: "The Supreme Person",
      description: "Understanding the ultimate reality.",
      moodTag: "Truth",
      icon: "☀️",
      duration: "16:50",
      category: "modern-gita",
      // videoPath: require('../assets/videos/modern-gita/15-supreme-person.mp4'),
    },
    {
      id: "mg-16",
      title: "Faith and Its Fruits",
      description: "How faith shapes our reality and experience.",
      moodTag: "Faith",
      icon: "🌟",
      duration: "14:25",
      category: "modern-gita",
      // videoPath: require('../assets/videos/modern-gita/16-faith-fruits.mp4'),
    },
    {
      id: "mg-17",
      title: "Renunciation and Liberation",
      description: "The art of letting go to find freedom.",
      moodTag: "Freedom",
      icon: "🕊️",
      duration: "18:10",
      category: "modern-gita",
      // videoPath: require('../assets/videos/modern-gita/17-renunciation.mp4'),
    },
    {
      id: "mg-18",
      title: "The Ultimate Teaching",
      description: "Krishna's final message for the modern seeker.",
      moodTag: "Completion",
      icon: "🏆",
      duration: "25:00",
      category: "modern-gita",
      // videoPath: require('../assets/videos/modern-gita/18-ultimate-teaching.mp4'),
    },
  ],
  "modern-reset": [
    {
      id: "mr-1",
      title: "Digital Detox Reset",
      description: "Breaking free from screen addiction in 10 minutes.",
      moodTag: "Detox",
      icon: "📱",
      duration: "10:00",
      category: "modern-reset",
      // videoPath: require('../assets/videos/modern-reset/01-digital-detox.mp4'),
    },
    {
      id: "mr-2",
      title: "Anxiety Emergency Reset",
      description: "Quick techniques to calm an anxious mind.",
      moodTag: "Calm",
      icon: "🌊",
      duration: "8:30",
      category: "modern-reset",
      // videoPath: require('../assets/videos/modern-reset/02-anxiety-reset.mp4'),
    },
    {
      id: "mr-3",
      title: "Focus Reset",
      description: "Regain concentration after distraction.",
      moodTag: "Focus",
      icon: "🎯",
      duration: "7:15",
      category: "modern-reset",
      // videoPath: require('../assets/videos/modern-reset/03-focus-reset.mp4'),
    },
    {
      id: "mr-4",
      title: "Emotional Reset",
      description: "Processing difficult emotions in real-time.",
      moodTag: "Release",
      icon: "💧",
      duration: "12:20",
      category: "modern-reset",
      // videoPath: require('../assets/videos/modern-reset/04-emotional-reset.mp4'),
    },
    {
      id: "mr-5",
      title: "Energy Reset",
      description: "Revitalize when you're feeling drained.",
      moodTag: "Energy",
      icon: "⚡",
      duration: "9:45",
      category: "modern-reset",
      // videoPath: require('../assets/videos/modern-reset/05-energy-reset.mp4'),
    },
  ],
  "lifestyle-os": [
    {
      id: "lo-1",
      title: "Morning Ritual Design",
      description: "Creating a morning routine that sets you up for success.",
      moodTag: "Morning",
      icon: "🌅",
      duration: "15:30",
      category: "lifestyle-os",
      // videoPath: require('../assets/videos/lifestyle-os/01-morning-ritual.mp4'),
    },
    {
      id: "lo-2",
      title: "Digital Minimalism",
      description: "Simplifying your relationship with technology.",
      moodTag: "Simplicity",
      icon: "📵",
      duration: "18:45",
      category: "lifestyle-os",
      // videoPath: require('../assets/videos/lifestyle-os/02-digital-minimalism.mp4'),
    },
    {
      id: "lo-3",
      title: "Conscious Consumption",
      description: "Making mindful choices about what you consume.",
      moodTag: "Mindful",
      icon: "🍃",
      duration: "14:20",
      category: "lifestyle-os",
      // videoPath: require('../assets/videos/lifestyle-os/03-conscious-consumption.mp4'),
    },
    {
      id: "lo-4",
      title: "Evening Wind-Down",
      description: "Preparing your mind and body for restful sleep.",
      moodTag: "Evening",
      icon: "🌙",
      duration: "16:10",
      category: "lifestyle-os",
      // videoPath: require('../assets/videos/lifestyle-os/04-evening-winddown.mp4'),
    },
    {
      id: "lo-5",
      title: "Weekly Review Practice",
      description: "Reflecting and planning for continuous growth.",
      moodTag: "Review",
      icon: "📊",
      duration: "20:00",
      category: "lifestyle-os",
      // videoPath: require('../assets/videos/lifestyle-os/05-weekly-review.mp4'),
    },
    {
      id: "lo-6",
      title: "Seasonal Living",
      description: "Aligning your lifestyle with nature's rhythms.",
      moodTag: "Rhythm",
      icon: "🍂",
      duration: "17:35",
      category: "lifestyle-os",
      // videoPath: require('../assets/videos/lifestyle-os/06-seasonal-living.mp4'),
    },
  ],
  "9-problems-9-solutions": [
    {
      id: "ps-1",
      title: "Overwhelm → Priority",
      description: "Finding clarity when everything feels urgent.",
      moodTag: "Clarity",
      icon: "🎯",
      duration: "12:15",
      category: "9-problems-9-solutions",
      // videoPath: require('../assets/videos/9-problems/01-overwhelm.mp4'),
    },
    {
      id: "ps-2",
      title: "Procrastination → Action",
      description: "Breaking through resistance and taking the first step.",
      moodTag: "Action",
      icon: "🚀",
      duration: "14:30",
      category: "9-problems-9-solutions",
      // videoPath: require('../assets/videos/9-problems/02-procrastination.mp4'),
    },
    {
      id: "ps-3",
      title: "Anxiety → Acceptance",
      description: "Making peace with uncertainty and lack of control.",
      moodTag: "Acceptance",
      icon: "🤲",
      duration: "16:45",
      category: "9-problems-9-solutions",
      // videoPath: require('../assets/videos/9-problems/03-anxiety.mp4'),
    },
    {
      id: "ps-4",
      title: "Comparison → Contentment",
      description: "Finding joy in your own unique journey.",
      moodTag: "Contentment",
      icon: "😊",
      duration: "13:20",
      category: "9-problems-9-solutions",
      // videoPath: require('../assets/videos/9-problems/04-comparison.mp4'),
    },
    {
      id: "ps-5",
      title: "Burnout → Balance",
      description: "Recovering energy and finding sustainable rhythms.",
      moodTag: "Balance",
      icon: "⚖️",
      duration: "18:10",
      category: "9-problems-9-solutions",
      // videoPath: require('../assets/videos/9-problems/05-burnout.mp4'),
    },
    {
      id: "ps-6",
      title: "Loneliness → Connection",
      description: "Building meaningful relationships in a disconnected world.",
      moodTag: "Connection",
      icon: "🤝",
      duration: "15:55",
      category: "9-problems-9-solutions",
      // videoPath: require('../assets/videos/9-problems/06-loneliness.mp4'),
    },
    {
      id: "ps-7",
      title: "Self-Doubt → Self-Trust",
      description: "Developing confidence in your own wisdom.",
      moodTag: "Trust",
      icon: "💪",
      duration: "17:25",
      category: "9-problems-9-solutions",
      // videoPath: require('../assets/videos/9-problems/07-self-doubt.mp4'),
    },
    {
      id: "ps-8",
      title: "Anger → Understanding",
      description: "Transforming frustration into compassionate action.",
      moodTag: "Understanding",
      icon: "🧠",
      duration: "14:40",
      category: "9-problems-9-solutions",
      // videoPath: require('../assets/videos/9-problems/08-anger.mp4'),
    },
    {
      id: "ps-9",
      title: "Meaninglessness → Purpose",
      description: "Discovering what truly matters to you.",
      moodTag: "Purpose",
      icon: "🌟",
      duration: "20:30",
      category: "9-problems-9-solutions",
      // videoPath: require('../assets/videos/9-problems/09-meaninglessness.mp4'),
    },
    {
      id: "ps-10",
      title: "Integration Practice",
      description: "Bringing all the solutions together into daily life.",
      moodTag: "Integration",
      icon: "🔗",
      duration: "22:15",
      category: "9-problems-9-solutions",
      // videoPath: require('../assets/videos/9-problems/10-integration.mp4'),
    },
  ],
};

// Helper function to get items by category
export const getCollectionItems = (categoryId: string): CollectionItem[] => {
  return collectionItems[categoryId] || [];
};

// Helper function to get a single item by ID
export const getCollectionItemById = (
  categoryId: string,
  itemId: string,
): CollectionItem | undefined => {
  return collectionItems[categoryId]?.find((item) => item.id === itemId);
};
